routes/web.php
<?php

use App\Http\Controllers\admin\JobController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\candidate\CandidateController;
use App\Http\Controllers\candidate\BrowseJobController;
use App\Http\Controllers\candidate\ProfileController;
use App\Http\Controllers\candidate\UploadController;
use App\Http\Controllers\candidate\YourCvController;
use App\Http\Controllers\employer\HomeController;
use App\Http\Controllers\employer\ListCandidateController;
use App\Http\Controllers\employer\PostJobController;
use App\Http\Controllers\employer\ProfileEmployerController;
use App\Http\Controllers\employer\RechargeController;
use AuthController as GlobalAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('auth')->group(function () {
    Route::get('/login', [AuthController::class, 'showFormLogin'])->name('show_form.login');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    Route::get('/register', [AuthController::class, 'showFormRegister'])->name('show_form.register');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware('checkLogin')->group(function () {
    Route::prefix('candidate')->middleware('candidate')->group(function () {
        Route::resource('candidate', CandidateController::class);
        Route::resource('browseJob', BrowseJobController::class);
        Route::resource('profile', ProfileController::class);
        Route::get('upload_cv', [UploadController::class, 'index'])->name('show_form.upload');
        Route::post('upload_cv', [UploadController::class, 'uploadCV'])->name('uploadCV');
        Route::get('/your_cv', [YourCvController::class, 'index'])->name('candidate.your_cv');
        Route::get('/viewFile', [YourCvController::class, 'viewFile'])->name('viewFile');
        Route::post('/pickMainCv', [YourCvController::class, 'pickMainCv'])->name('pickMainCv');
    });

    Route::prefix('employer')->middleware('employer')->group(function () {
        Route::get('/index', [HomeController::class, 'index'])->name('employer.index');
        Route::get('/employer', [RechargeController::class, 'index'])->name('employer.recharge');
        Route::post('/employer', [RechargeController::class, 'updateMoney'])->name('employer.updateRechare');
        Route::resource('profileEmployer', ProfileEmployerController::class);
        Route::get('/postJob', [PostJobController::class, 'index'])->name('employer.post_job');
        Route::post('/postJob', [PostJobController::class, 'create'])->name('employer.create');
        Route::get('/list_candidate', [ListCandidateController::class, 'index'])->name('employer.list_candidate');
        Route::post('/list_candidate', [ListCandidateController::class, 'showCv'])->name('showCv.list_candidate');
    });
});

Route::prefix('admin')->group(function () {
    Route::get('/index', function () {
        return view('admin.index');
    })->name('index');
    Route::resource('job', JobController::class);
    Route::resource('user', UserController::class);
});

app/Http/Controllers/candidate/BrowseJobController.php
<?php

namespace App\Http\Controllers\candidate;

use App\Http\Controllers\Controller;
use App\Models\Job;
use App\Models\Candidate;
use Illuminate\Http\Request;
use App\Services\candidate\JobService;
use App\Http\Requests\CandidateApplyRequest;
use App\Services\candidate\CvUserService;
use Throwable;

class BrowseJobController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $jobService;
    protected $cvUserService;

    public function __construct(JobService $jobService, CvUserService $cvUserService)
    {
        $this->jobService = $jobService;
        $this->cvUserService = $cvUserService;
    }

    public function index()
    {
        try {
            $jobs = $this->jobService->getSearchJob();
            $idMainCv = $jobs['idMainCv'];
            $jobs = $jobs['jobs'];
            if ($jobs->count() == 0) {
                return view('candidate.browsejobs');
            } else {
                return view('candidate.browsejobs', compact('jobs', 'idMainCv'));
            }
        } catch (Throwable $e) {
            return abort(404);
        }
    }

    public function store(CandidateApplyRequest $request)
    {
        try {
            $request = $request->only(['cv_id', 'employer_id']);
            $candidateApply = $this->cvUserService->addCandidateApply($request);
            return redirect(route('browseJob.index'))->with('applySuccess', 'Bạn đã ứng tuyển thành công, chúc mừng bạn !!!');
        } catch (Throwable $e) {
            return abort(404);
        }
    }
}

app/Http/Controllers/candidate/CandidateController.php
<?php

namespace App\Http\Controllers\candidate;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Job;
use App\Services\candidate\JobService;
use Throwable;

class CandidateController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    protected $jobService;

    public function __construct(JobService $jobService)
    {
        $this->jobService = $jobService;
    }

    public function index()
    {
        //
        try {
            $jobs = $this->jobService->getJob();
            return view('candidate.index', compact('jobs'));
        } catch (Throwable $e) {
            return abort(404);
        }
    }

}

app/Http/Controllers/candidate/ProfileController.php
<?php

namespace App\Http\Controllers\candidate;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Services\candidate\ProfileService;
use App\Http\Requests\UpdateProfileRequest;
use App\Models\Image;
use Throwable;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    protected $profileService;

    public function __construct(ProfileService $profileService)
    {
        $this->profileService = $profileService;
    }

    public function index()
    {
        //
        try {
            $img = $this->profileService->getImg();
            $user = $this->profileService->getInfoUser();
            return view('candidate.profile', compact('user', 'img'));
        } catch (Throwable $e) {
            return abort(404);
        }
    }

    public function update(UpdateProfileRequest $request, string $id)
    {
        //
        try {
            $requestImg = $request->only(['file']);
            if ($requestImg) {
                $img = $this->profileService->createImg($requestImg);
            }
            $request = $request->only(['id', 'user_name', 'phone_number', 'degree', 'experience']);
            $data = $this->profileService->updateInfo($request);
            return redirect(route('profile.index'));
        } catch (Throwable $e) {
            return abort(404);
        }
    }
}

app/Http/Controllers/candidate/UploadController.php
<?php

namespace App\Http\Controllers\candidate;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Cv;
use App\Http\Requests\UploadRequest;
use Illuminate\Support\Facades\Auth;
use App\Services\candidate\UploadService;
use Throwable;

class UploadController extends Controller
{
    //
    protected $uploadService;

    public function __construct(UploadService $uploadService)
    {
        $this->uploadService = $uploadService;
    }
    public function index()
    {
        return view('candidate.upload_cv');
    }

    public function uploadCV(UploadRequest $request)
    {   
        try {
            $data = $request->only(['user_id', 'title', 'upload']);
            $cv = $this->uploadService->uploadCv($data);
            if ($cv) {
                return redirect(route('candidate.your_cv'));
            }
        } catch(Throwable $e) {
            return abort(404);
        }   
    }
}

app/Http/Controllers/candidate/YourCvController.php
<?php

namespace App\Http\Controllers\candidate;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\candidate\IndexService;
use Illuminate\Support\Facades\Storage;
use App\Models\Cv;
use App\Services\candidate\UploadService;
use Throwable;

class YourCvController extends Controller
{
    //
    protected $indexService;
    protected $uploadService;

    public function __construct(UploadService $uploadService)
    {
        $this->uploadService = $uploadService;
    }

    public function index()
    {
        try {
            $id = Cv::where('status', 1)->pluck('id');
            $cvs = $this->uploadService->getCv();
            return view('candidate.your_cv', compact('cvs', 'id'));
        } catch (Throwable $e) {
            return abort(404);
        }
    }

    public function viewFile()
    {
        try {
            $request = request()->fileName;
            $viewFile = $this->uploadService->viewFile($request);
            return $viewFile;
        } catch (Throwable $e) {
            return abort(404);
        }
    }

    public function pickMainCv(Request $request)
    {
        try {
            $request = $request->only('id');
            $pickMainCv = $this->uploadService->pickMainCv($request);
            return redirect(route('candidate.your_cv'));
        } catch (Throwable $e) {
            return abort(404);
        }
    }
}

resources/views/candidate/browsejobs.blade.php
@extends('layout')

@section('content')
    <div class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-start">
                <div class="col-md-12 ftco-animate text-center mb-5">
                    <p class="breadcrumbs mb-0"><span class="mr-3"><a href="index.html">Home <i
                                    class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p>
                    <h1 class="mb-3 bread">Browse Jobs</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section ftco-no-pb bg-light">
        <div class="container">
            <div class="row">
                <div class="ftco-search">
                    <div class="row">
                        <div class="col-md-12 nav-link-wrap">
                        </div>
                        <div class="col-md-12 tab-wrap">
                            <div class="tab-content p-4" id="v-pills-tabContent">
                                <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel"
                                    aria-labelledby="v-pills-nextgen-tab">
                                    <form action="{{ route('browseJob.store') }}" class="search-job" method="Get">
                                        @csrf
                                        <div class="row no-gutters">
                                            <div class="col-md mr-md-2">
                                                <div class="form-group">
                                                    <div class="form-field">
                                                        <div class="icon"><span class="icon-briefcase"></span></div>
                                                        <input type="text" class="form-control" placeholder="Fill title"
                                                            name="title">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md mr-md-2">
                                                <div class="form-group">
                                                    <div class="form-field">
                                                        <div class="icon"><span class="icon-briefcase"></span></div>
                                                        <input type="text" class="form-control" placeholder="Fill time"
                                                            name="time">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md mr-md-2">
                                                <div class="form-group">
                                                    <div class="form-field">
                                                        <div class="icon"><span class="icon-map-marker"></span></div>
                                                        <input type="text" class="form-control" placeholder="Location"
                                                            name="location">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md">
                                                <div class="form-group">
                                                    <div class="form-field">
                                                        <button type="submit"
                                                            class="form-control btn btn-primary">Search</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 pr-lg-4">

                    @if (session('applySuccess'))
                        <center>
                            <p style="color:#206dfb ; font-size:26px">{{ session('applySuccess') }}</p>
                        </center>
                    @endif

                    @if (isset($jobs))
                        @foreach ($jobs as $job)
                            <form action="{{ route('browseJob.store') }}" method="POST">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12 ftco-animate">
                                        <div class="job-post-item p-4 d-block d-lg-flex align-items-center">
                                            <div class="one-third mb-4 mb-md-0">
                                                <div class="job-post-item-header align-items-center">
                                                    <span class="subadge">{{ $job->time }}</span>
                                                    <h2 class="mr-3 text-black"><a href="#">{{ $job->title }}</a>
                                                    </h2>
                                                </div>
                                                @foreach ($idMainCv as $id)
                                                    <input type="hidden" value="{{ $id }}" name="cv_id">
                                                @endforeach
                                                <input type="hidden" name="employer_id" value="{{ $job->employer_id }}">
                                                <div class="job-post-item-body d-block d-md-flex">
                                                    <div class="mr-3"><span class="icon-layers"></span> <a
                                                            href="#">{{ $job->status }}</a></div>
                                                    <div><span class="icon-my_location"></span>
                                                        <span>{{ $job->location }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="one-forth ml-auto d-flex align-items-center mt-4 md-md-0">
                                                <div>
                                                    <a href="#"
                                                        class="icon text-center d-flex justify-content-center align-items-center icon mr-2">
                                                        <span class="icon-heart"></span>
                                                    </a>
                                                </div>
                                                <button type="submit" class="btn btn-primary py-2">Apply Job</button>
                                            </div>
                                        </div>
                                    </div><!-- end -->
                                </div>
                            </form>
                        @endforeach
                        {{ $jobs->withQueryString()->links() }}
                    @else
                        <div class="alert alert-primary" role="alert">
                            <center>NOT DATA, CLICK SEARCH TO FIND JOBS !</center>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/candidate/profile.blade.php
@extends('layout')

@section('content')
    <div class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-start">
                <div class="col-md-12 ftco-animate text-center mb-5">
                    <p class="breadcrumbs mb-0"><span class="mr-3"><a href="index.html">Home <i
                                    class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p>
                    <h1 class="mb-3 bread">Profile</h1>
                </div>
            </div>
        </div>
    </div>

    <head>
        <style>
            .container.py-5.new {
                background-color: white;
            }
        </style>
    </head>
    <div class="container-xxl bg-white p-0">
        <!-- END nav -->
        <section style="background-color: #eee;">
            <div class="container py-5 new">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-body text-center" style="height:356px">
                                @foreach ($img as $imgs)
                                    <img src="{{ asset('storage/' . $imgs) }}" alt="avatar"
                                        class="rounded-circle img-fluid" style="width: 200px; height:200px">
                                @endforeach
                                <h5 class="my-3" style="color: red"></h5>
                                <p class="text-muted mb-1"></p>
                                <p class="text-muted mb-4"><a href=""></a></p>
                                <div class="d-flex justify-content-center mb-2">
                                    @foreach ($user as $users)
                                        <form action="{{ route('profile.update', ['profile' => $users->id]) }}"
                                            method="POST" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <input type="file" name="file" class="" id="uploadImage"
                                                accept=".jpg, .png">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Họ và tên</p>
                                    </div>
                                    <input type="hidden" name="id" value="{{ $users->id }}">
                                    <div class="col-sm-9">
                                        <input name="user_name" style="border:none; width:440px" class="text-muted mb-0"
                                            value="{{ $users->user_name }}" />
                                        @error('user_name')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Email</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ $users->email }}
                                        </p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Số điện thoại</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <input name="phone_number" style="border:none; width:440px" class="text-muted mb-0"
                                            value="{{ $users->phone_number }}" />
                                        @error('phone_number')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Bằng cấp</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <input name="degree" style="border:none; width:440px" class="text-muted mb-0"
                                            value="{{ $users->degree }}" />
                                        @error('degree')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Kinh nghiệm</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <input name="experience" style="border:none; width:440px" class="text-muted mb-0"
                                            value="{{ $users->experience }}" />
                                        @error('experience')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <hr>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-secondary"
                    style="float:right;color: #00B074;background-color: aliceblue">Cập
                    nhật</button>
                </form>
                @endforeach
            </div>
        </section>
    </div>
@endsection

resources/views/candidate/upload_cv.blade.php
@extends('layout')

@section('content')
    <div class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-start">
                <div class="col-md-12 ftco-animate text-center mb-5">
                    <p class="breadcrumbs mb-0"><span class="mr-3"><a href="index.html">Home <i
                                    class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p>
                    <h1 class="mb-3 bread">Upload Your CV</h1>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row">

                <div class="col-md-12 col-lg-8 mb-5">

                    <form action="{{ route('uploadCV') }}" class="p-5 bg-white" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row form-group">
                            <div class="col-md-12 mb-3 mb-md-0">
                                <label class="font-weight-bold" for="fullname">TITLE OF CV</label>
                                <input type="text" id="fullname" class="form-control" placeholder="Fill title in here"
                                    name="title" value="{{old('title')}}" >
                                @error('title')
                                    <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                @enderror
                            </div>

                        </div>
                        <input type="hidden" name="user_id" value="{{ Auth::id() }}">
                        <div class="row form-group mb-4">
                            <div class="col-md-12">
                                <h3>Upload CV Here</h3>
                            </div>
                            <div class="col-md-12 mb-3 mb-md-0">
                                <input class="form-control" type="file" id="formFileDisabled" name="upload" accept=".docx,.pdf">
                                @error('upload')
                                    <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                @enderror
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <h3>Dream Job</h3>
                            </div>
                            <div class="col-md-12 mb-3 mb-md-0">
                                <textarea name="" class="form-control" id="" cols="30" rows="5"></textarea>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Post" class="btn btn-primary  py-2 px-5">
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-lg-4">
                    <div class="p-4 mb-3 bg-white">
                        <h3 class="h5 text-black mb-3">Contact Info</h3>
                        <p class="mb-0 font-weight-bold">Address</p>
                        <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

                        <p class="mb-0 font-weight-bold">Phone</p>
                        <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

                        <p class="mb-0 font-weight-bold">Email Address</p>
                        <p class="mb-0"><a href="#"><span class="__cf_email__"
                                    data-cfemail="671e081215020a060e0b2703080a060e094904080a">[email&#160;protected]</span></a>
                        </p>

                    </div>

                    <div class="p-4 mb-3 bg-white">
                        <h3 class="h5 text-black mb-3">More Info</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto
                            hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
                        <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section-parallax">
        <div class="parallax-img d-flex align-items-center">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
                        <h2>Subcribe to our Newsletter</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                            live the blind texts. Separated they live in</p>
                        <div class="row d-flex justify-content-center mt-4 mb-4">
                            <div class="col-md-12">
                                <form action="#" class="subscribe-form">
                                    <div class="form-group d-flex">
                                        <input type="text" class="form-control" placeholder="Enter email address">
                                        <input type="submit" value="Subscribe" class="submit px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection