routes/web.php
<?php

use App\Http\Controllers\admin\JobController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\candidate\CandidateController;
use App\Http\Controllers\candidate\BrowseJobController;
use App\Http\Controllers\candidate\ProfileController;
use App\Http\Controllers\candidate\UploadController;
use App\Http\Controllers\candidate\YourCvController;
use App\Http\Controllers\employer\HomeController;
use App\Http\Controllers\employer\ListCandidateController;
use App\Http\Controllers\employer\PostJobController;
use App\Http\Controllers\employer\ProfileEmployerController;
use App\Http\Controllers\employer\RechargeController;
use AuthController as GlobalAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('auth')->group(function () {
    Route::get('/login', [AuthController::class, 'showFormLogin'])->name('show_form.login');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    Route::get('/register', [AuthController::class, 'showFormRegister'])->name('show_form.register');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware('checkLogin')->group(function () {
    Route::prefix('candidate')->middleware('candidate')->group(function () {
        Route::resource('candidate', CandidateController::class);
        Route::resource('browseJob', BrowseJobController::class);
        Route::resource('profile', ProfileController::class);
        Route::get('upload_cv', [UploadController::class, 'index'])->name('show_form.upload');
        Route::post('upload_cv', [UploadController::class, 'uploadCV'])->name('uploadCV');
        Route::get('/your_cv', [YourCvController::class, 'index'])->name('candidate.your_cv');
        Route::get('/viewFile', [YourCvController::class, 'viewFile'])->name('viewFile');
        Route::post('/pickMainCv', [YourCvController::class, 'pickMainCv'])->name('pickMainCv');
    });

    Route::prefix('employer')->middleware('employer')->group(function () {
        Route::get('/index', [HomeController::class, 'index'])->name('employer.index');
        Route::get('/employer', [RechargeController::class, 'index'])->name('employer.recharge');
        Route::post('/employer', [RechargeController::class, 'updateMoney'])->name('employer.updateRechare');
        Route::resource('profileEmployer', ProfileEmployerController::class);
        Route::get('/postJob', [PostJobController::class, 'index'])->name('employer.post_job');
        Route::post('/postJob', [PostJobController::class, 'create'])->name('employer.create');
        Route::get('/list_candidate', [ListCandidateController::class, 'index'])->name('employer.list_candidate');
        Route::post('/list_candidate', [ListCandidateController::class, 'showCv'])->name('showCv.list_candidate');
    });
});

Route::prefix('admin')->group(function () {
    Route::get('/index', function () {
        return view('admin.index');
    })->name('index');
    Route::resource('job', JobController::class);
    Route::resource('user', UserController::class);
});

resources/views/layout/footer.blade.php
<section class="ftco-section-parallax">
    <div class="parallax-img d-flex align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
                    <h2>Subcribe to our Newsletter</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts. Separated they live in</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-12">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Skillhunt Jobboard</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Employers</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="pb-1 d-block">Browse Candidates</a></li>
                        <li><a href="#" class="pb-1 d-block">Post a Job</a></li>
                        <li><a href="#" class="pb-1 d-block">Employer Listing</a></li>
                        <li><a href="#" class="pb-1 d-block">Resume Page</a></li>
                        <li><a href="#" class="pb-1 d-block">Dashboard</a></li>
                        <li><a href="#" class="pb-1 d-block">Job Packages</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Candidate</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="pb-1 d-block">Browse Jobs</a></li>
                        <li><a href="#" class="pb-1 d-block">Submit Resume</a></li>
                        <li><a href="#" class="pb-1 d-block">Dashboard</a></li>
                        <li><a href="#" class="pb-1 d-block">Browse Categories</a></li>
                        <li><a href="#" class="pb-1 d-block">My Bookmarks</a></li>
                        <li><a href="#" class="pb-1 d-block">Candidate Listing</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Account</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="pb-1 d-block">My Account</a></li>
                        <li><a href="#" class="pb-1 d-block">Sign In</a></li>
                        <li><a href="#" class="pb-1 d-block">Create Account</a></li>
                        <li><a href="#" class="pb-1 d-block">Checkout</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain
                                    View, San Francisco, California, USA</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392
                                        3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span
                                        class="text">info@yourdomain.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script> All rights reserved | This template is made with <i
                        class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4"
            stroke="#eeeeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4"
            stroke-miterlimit="10" stroke="#F96D00" />
    </svg></div>

resources/views/layout/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container-fluid px-md-4	">
        <a class="navbar-brand" href="index.html">Skillhunt</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{{ route('candidate.index') }}" class="nav-link">Home</a></li>
                <li class="nav-item active"><a href="{{ route('browseJob.index') }}" class="nav-link">Browse
                    Jobs</a></li>
                <li class="nav-item"><a href="{{ route('profile.index') }}" class="nav-link">Profile</a></li>
                <li class="nav-item"><a href="{{ route('candidate.your_cv') }}" class="nav-link">Your CV</a></li>
                <li class="nav-item cta mr-md-1"><a href="{{ route('show_form.upload') }}" class="nav-link">Upload
                        your CV</a></li>
                @if (!Auth::check())
                    <li class="nav-item cta cta-colored"><a href="{{ route('show_form.login') }}"
                            class="nav-link">Login</a></li>
                @else
                    <li class="nav-item cta cta-colored"><a href="{{ route('logout') }}" class="nav-link">Logout</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->