routes/web.php
<?php

use App\Http\Controllers\admin\JobController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\candidate\CandidateController;
use App\Http\Controllers\candidate\BrowseJobController;
use App\Http\Controllers\candidate\ProfileController;
use App\Http\Controllers\candidate\UploadController;
use App\Http\Controllers\candidate\YourCvController;
use App\Http\Controllers\employer\HomeController;
use App\Http\Controllers\employer\ListCandidateController;
use App\Http\Controllers\employer\PostJobController;
use App\Http\Controllers\employer\ProfileEmployerController;
use App\Http\Controllers\employer\RechargeController;
use AuthController as GlobalAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('auth')->group(function () {
    Route::get('/login', [AuthController::class, 'showFormLogin'])->name('show_form.login');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    Route::get('/register', [AuthController::class, 'showFormRegister'])->name('show_form.register');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::middleware('checkLogin')->group(function () {
    Route::prefix('candidate')->middleware('candidate')->group(function () {
        Route::resource('candidate', CandidateController::class);
        Route::resource('browseJob', BrowseJobController::class);
        Route::resource('profile', ProfileController::class);
        Route::get('upload_cv', [UploadController::class, 'index'])->name('show_form.upload');
        Route::post('upload_cv', [UploadController::class, 'uploadCV'])->name('uploadCV');
        Route::get('/your_cv', [YourCvController::class, 'index'])->name('candidate.your_cv');
        Route::get('/viewFile', [YourCvController::class, 'viewFile'])->name('viewFile');
        Route::post('/pickMainCv', [YourCvController::class, 'pickMainCv'])->name('pickMainCv');
    });

    Route::prefix('employer')->middleware('employer')->group(function () {
        Route::get('/index', [HomeController::class, 'index'])->name('employer.index');
        Route::get('/employer', [RechargeController::class, 'index'])->name('employer.recharge');
        Route::post('/employer', [RechargeController::class, 'updateMoney'])->name('employer.updateRechare');
        Route::resource('profileEmployer', ProfileEmployerController::class);
        Route::get('/postJob', [PostJobController::class, 'index'])->name('employer.post_job');
        Route::post('/postJob', [PostJobController::class, 'create'])->name('employer.create');
        Route::get('/list_candidate', [ListCandidateController::class, 'index'])->name('employer.list_candidate');
        Route::post('/list_candidate', [ListCandidateController::class, 'showCv'])->name('showCv.list_candidate');
    });
});

Route::prefix('admin')->group(function () {
    Route::get('/index', function () {
        return view('admin.index');
    })->name('index');
    Route::resource('job', JobController::class);
    Route::resource('user', UserController::class);
});

resources/views/admin/create_job.blade.php
@extends('layout_admin')

@section('content')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-5">
                    <h4 class="page-title">Job Page</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Library</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <!-- Column -->
                <!-- Column -->
                <div class="col-lg-12 col-xlg-9 col-md-7">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal form-material mx-2" action="{{ route('job.store') }}"
                                method="POST">
                                @csrf
                                
                                <div class="form-group">
                                    <label class="col-sm-12">Select Employer Id</label>
                                    <div class="col-sm-12">
                                        <select class="form-select shadow-none form-control-line" name="employer_id">
                                            @foreach($employerId as $id)<option name="employer_id" value="{{ $id }}"> {{ $id }}</option> @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Title</label>
                                    <div class="col-md-12">
                                        <input type="text" placeholder="Fill title" class="form-control form-control-line"
                                            name="title" value="">
                                        @error('title')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Select Job Type</label>
                                    <div class="col-sm-12">
                                        <select class="form-select shadow-none form-control-line" name="time">
                                            <option name="time" value="Part Time">Part Time</option>
                                            <option name="time" value="Full Time">Full Time</option>
                                            <option name="time" value="Freelancer">Freelancer</option>
                                            <option name="time" value="Intership">Intership</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Lcoation</label>
                                    <div class="col-md-12">
                                        <input type="text" placeholder="Fill location"
                                            class="form-control form-control-line" value="" name="location">
                                        @error('location')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Description</label>
                                    <div class="col-md-12">
                                        <input rows="5" class="form-control form-control-line" name="description"
                                            value="">
                                        @error('description')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Status</label>
                                    <div class="col-md-12">
                                        <input type="text" class="form-control form-control-line" name="status"
                                            value="">
                                        @error('status')
                                            <p style="color: #dd3675;padding-top:4px">* {{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-success text-white">Create New Job</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>
            <!-- Row -->
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
            All Rights Reserved by Xtreme Admin. Designed and Developed by <a
                href="https://www.wrappixel.com">WrapPixel</a>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
@endsection

resources/views/admin/table_job.blade.php
@extends('layout_admin')

@section('content')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-5">
                    <h4 class="page-title">Job Table</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Library</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-7">
                    <div class="text-end upgrade-btn">
                        <a href="{{ route('job.create') }}" class="btn btn-danger text-white" target="_blank">Add New
                            Job</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Job Table</h4>
                            <h6 class="card-title m-t-40"><i
                                    class="m-r-5 font-18 mdi mdi-numeric-1-box-multiple-outline"></i> Table With
                                Outside Padding</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col" style="text-align:center">#</th>
                                            <th scope="col" style="text-align:center">EmployId</th>
                                            <th scope="col" style="text-align:center">Title</th>
                                            <th scope="col" style="text-align:center">Job Type</th>
                                            <th scope="col" style="text-align:center">Location</th>
                                            <th scope="col" style="text-align:center">Description</th>
                                            <th scope="col" style="text-align:center">Status</th>
                                            <th scope="col" style="text-align:center">Operation</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($job as $key => $jobs)
                                            <tr>
                                                <th scope="row" style="text-align:center">{{ $jobs->id }}</th>
                                                <td style="text-align:center">{{ $jobs->employer_id }}</td>
                                                <td style="text-align:center">{{ $jobs->title }}</td>
                                                <td style="text-align:center">{{ $jobs->time }}</td>
                                                <td style="text-align:center">{{ $jobs->location }}</td>
                                                <td style="text-align:center">{{ $jobs->description }}</td>
                                                <td style="text-align:center">{{ $jobs->status }}</td>
                                                <td>
                                                    <center>
                                                        <a href="{{ route('job.edit', ['job'=>$jobs->id]) }}"><i
                                                                class='far fa-edit'style='font-size:12px'></i></a>
                                                        <form action="{{ route('job.destroy', ['job'=>$jobs->id]) }}" method="POST">
                                                            @method('DELETE')
                                                            @csrf
                                                            <button><i style='font-size:12px'
                                                                    class='far'>&#xf2ed;</i></button>
                                                        </form>
                                                    </center>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                {{ $job->withQueryString()->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
            All Rights Reserved by Xtreme Admin. Designed and Developed by < href="https://www.wrappixel.com">WrapPixel</>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
@endsection

resources/views/admin/table_user.blade.php
@extends('layout_admin')

@section('content')
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-5">
                    <h4 class="page-title">User Table</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Library</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-7">
                    <div class="text-end upgrade-btn">
                        <a href="{{ route('user.create') }}" class="btn btn-danger text-white" target="_blank">Add New
                            User</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">User Table</h4>
                            <h6 class="card-title m-t-40"><i
                                    class="m-r-5 font-18 mdi mdi-numeric-1-box-multiple-outline"></i> Table With
                                Outside Padding</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col" style="text-align:center">#</th>
                                            <th scope="col" style="text-align:center">Name</th>
                                            <th scope="col" style="text-align:center">Email</th>
                                            <th scope="col" style="text-align:center">Phone</th>
                                            <th scope="col" style="text-align:center">Role</th>
                                            <th scope="col" style="text-align:center">Degree</th>
                                            <th scope="col" style="text-align:center">Experience</th>
                                            <th scope="col" style="text-align:center">Operation</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($user as $key => $users)
                                            <tr>
                                                <th scope="row" style="text-align:center">{{ $key++ }}</th>
                                                <td style="text-align:center">{{ $users->user_name }}</td>
                                                <td style="text-align:center">{{ $users->email }}</td>
                                                <td style="text-align:center">{{ $users->phone_number }}</td>
                                                <td style="text-align:center">
                                                    @if ($users->role == 0)
                                                        Candidate
                                                    @elseif($users->role == 1)
                                                        Employer
                                                    @endif
                                                </td>
                                                <td style="text-align:center">{{ $users->degree }}</td>
                                                <td style="text-align:center">{{ $users->experience }}</td>
                                                <td>
                                                    <center>
                                                        <a href="{{ route('user.edit', ['user' => $users->id]) }} "><i
                                                                class='far fa-edit'style='font-size:12px'></i></a>
                                                        <form action="{{ route('user.destroy', ['user' => $users->id]) }} "
                                                            method="POST">
                                                            @method('DELETE')
                                                            @csrf
                                                            <button><i style='font-size:12px'
                                                                    class='far'>&#xf2ed;</i></button>
                                                        </form>
                                                    </center>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
            All Rights Reserved by Xtreme Admin. Designed and Developed by < href="https://www.wrappixel.com">WrapPixel</>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
@endsection